name: proxy
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { crypto: ^3.0.2, dns_client: ^0.2.1, http: ^0.13.5, json5: ^0.8.0, maxminddb: ^1.2.0, quiver: ^3.1.0, uuid: ^3.0.6}
