name: proxy
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
dependencies: { crypto: ^3.0.2, cryptography: ^2.0.5, dcache: ^0.4.0, dns_client: ^0.2.1, grpc: ^3.1.0, http: ^0.13.5, http2: ^2.0.1, json5: ^0.8.0, logging: ^1.1.0, maxminddb: ^1.2.0, path: ^1.8.2, quiver: ^3.1.0, shelf: ^1.3.2, shelf_web_socket: ^1.0.2, stack_trace: ^1.11.0, uuid: ^3.0.6}
