name: build and publish
on: [push]

jobs:
  setup_env:
    name: build and publish
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get

      - name: Install dependencies
        run: dart compile exe ./bin/proxy.dart -o ./disk/RRS_${{ runner.os }}.exe

      - name: zip
        run: zip -r -q RRS_${{ runner.os }}.zip disk

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: './disk'
          filename: 'RRS_${{ runner.os }}.zip'

      - run: ls

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./RRS_${{ runner.os }}.zip
