name: build and publish
on: [push]

jobs:
  setup_env:
    name: build and publish
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'build')"
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart compile exe ./bin/proxy.dart -o ./RRS_${{ runner.os }}.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./RRS_${{ runner.os }}.exe
