name: test install
on: [push]

jobs:
  setup_env:
    name: test install
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, 'test')"
    steps:
      - run: sudo -i
      - name: test install
        run: bash <(curl https://raw.githubusercontent.com/JimmyHuang454/RRS/master/tools/install.sh)
