name: test
on: [push, pull_request]

jobs:
  setup_env:
    name: test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, 'test')"
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - run: dart pub get

      - name: test
        run: dart test --coverage=./coverage

      - name: generate coverage
        run: dart pub global activate coverage
        run: dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          verbose: true # optional (default = false)
